parameters:
    sheppers_rest_doc.doc.path: %kernel.root_dir%/../vendor/sheppers/rest-doc-bundle/src/Sheppers/RestDocBundle/Resources/doc

services:
#    sheppers_rest_doc.example:
#        class: %sheppers_rest_doc.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
