parameters:
#    sheppers_rest_doc.example.class: Sheppers\RestDocBundle\Example

services:
#    sheppers_rest_doc.example:
#        class: %sheppers_rest_doc.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
